name: test2

on:
  workflow_run:
    workflows:
      - test
    # branches: [ master ]
    types:
      - completed
  workflow_dispatch:
    inputs:
      countries:
        required: true
        type: string
        default: '"ae","eg"'
        description: String of comma separated country codes e.g. '"ae","eg","bh"'

env:
  DEFAULT_COUNTRIES: '"ae"'

jobs:
  cd:
    uses: Trezcool/.github/.github/workflows/test3.yml@main
    with:
      countries: ${{ inputs.countries || env.DEFAULT_COUNTRIES }}
