name: test3

on:
  workflow_call:
    inputs:
      country:
        required: true
        type: string

jobs:
  deploy:
    name: test3
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Smoke
        run: echo ${{ inputs.country }}
