name: test2

on:
  # workflow_run:
  #   workflows:
  #     - test
  #   # branches: [ master ]
  #   types:
  #     - completed
  workflow_dispatch:
    # inputs:
    #   countries:
    #     required: true
    #     type: string
    #     default: '"ae","eg"'
    #     description: String of comma separated country codes e.g. '"ae","eg","bh"'
  # issue_comment:
  #   types: [ created ]

jobs:
  cd:
    # name: OK
    # strategy:
    #   matrix:
    #     country: ${{ fromJson(format('[{0}]', inputs.countries)) }}
    # # uses: Trezcool/.github/.github/workflows/test3.yml@main
    # # with:
    # #   country: ${{ matrix.country }}
    runs-on: ubuntu-latest
    steps:
      # - name: Smoke
      #   env:
      #       DEBUG_CONTEXT: ${{ toJson(github) }}
      #   run: echo "$DEBUG_CONTEXT"

      - uses: Trezcool/.github/.github/actions/test
        with:
          environment: test
